language: minimal
sudo: false
addons:
  apt:
    packages:
    - lftp

before_script:
  - chmod +x upload.sh

after_success:
  - rm -r --interactive=never -f .idea
  - rm -r --interactive=never -f .git
  - rm -r --interactive=never -f Readme.md
  - rm -r --interactive=never -f .gitignore
  - ./upload.sh

branches:
  only:
  - master
