language: minimal
after_success:
  - find * -type f -print -exec curl -T {} ftp://102345.w45.wedos.net/www/domains/deboraaondrej.ludova-hudba.eu/{} -u $FTP_USER:$FTP_PASSWORD \;
branches:
  only:
  - master
